// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v5/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v5/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Actors = sequelize.define('actors', {
    firstName: {
      type: DataTypes.STRING,
    },
    lastName: {
      type: DataTypes.STRING,
    },
    gender: {
      type: DataTypes.STRING,
      defaultValue: Sequelize.literal('male'),
    },
    picture: {
      type: DataTypes.STRING,
    },
  }, {
    tableName: 'actors',
    underscored: true,
    timestamps: false,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v5/reference-guide/relationships#adding-relationships.
  Actors.associate = (models) => {
    Actors.hasMany(models.roles, {
      foreignKey: {
        name: 'actorIdKey',
        field: 'actor_id',
        // allowNull: false,
      },
      as: 'roles',
    });
  };

  return Actors;
};
