// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v5/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v5/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Roles = sequelize.define('roles', {
    name: {
      type: DataTypes.STRING,
    },
    leadRole: {
      type: DataTypes.BOOLEAN,
    },
    // actorId: {
    //   field: 'actor_id',
    //   type: DataTypes.NUMBER,
    //   allowNull: false,
    // },
  }, {
    tableName: 'roles',
    underscored: true,
    timestamps: false,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v5/reference-guide/relationships#adding-relationships.
  Roles.associate = (models) => {
    Roles.belongsTo(models.actors, {
      foreignKey: {
        name: 'actorIdKey',
        field: 'actor_id',
      },
      as: 'actor',
    });
    Roles.belongsTo(models.movies, {
      foreignKey: {
        name: 'movieIdKey',
        field: 'movie_id',
      },
      as: 'movie',
    });
  };

  return Roles;
};
